spring:
  ai:
    model:
      chat: ollama
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2-vision
      embedding:
        model: llama3.2-vision
  http:
    client:
      read-timeout: 600000
      connect-timeout: 600000